name: Build & push demo bundle

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to push to
        type: choice
        required: true
        default: dev
        options:
          - dev
          - US
          - EU

jobs:
  dev:
    if: github.event_name == 'push' || inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-push-demo-bundle
        with:
          node-version: ${{ vars.BUILD_NODE_VERSION }}
          api-key: ${{ secrets.EMBEDDABLE_API_KEY_DEV }}
          email: ${{ vars.EMBEDDABLE_PUSH_EMAIL }}
          message: Auto-push from ${{ github.sha }}
          config-patch: |
            sed -i -E 's#^(\s*)region: "US",#\1// region: "US",#' embeddable.config.ts
            sed -i -E 's#^(\s*)// (previewBaseUrl|pushBaseUrl|audienceUrl|authDomain|authClientId):#\1\2:#' embeddable.config.ts

  US:
    if: github.event_name == 'push' || inputs.environment == 'US'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-push-demo-bundle
        with:
          node-version: ${{ vars.BUILD_NODE_VERSION }}
          api-key: ${{ secrets.EMBEDDABLE_API_KEY_US }}
          email: ${{ vars.EMBEDDABLE_PUSH_EMAIL }}
          message: Auto-push from ${{ github.sha }}

  EU:
    if: github.event_name == 'push' || inputs.environment == 'EU'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-push-demo-bundle
        with:
          node-version: ${{ vars.BUILD_NODE_VERSION }}
          api-key: ${{ secrets.EMBEDDABLE_API_KEY_EU }}
          email: ${{ vars.EMBEDDABLE_PUSH_EMAIL }}
          message: Auto-push from ${{ github.sha }}
          config-patch: sed -i 's/"US"/"EU"/' embeddable.config.ts
